networks:
  back:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "ng serve --host 0.0.0.0"
    ports:
      - 127.0.0.1:4200:4200
    networks:
      - back

  db:
    container_name: database

    image: mariadb:latest
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: administration
      MYSQL_USER: user
      MYSQL_PASSWORD: example

    networks:
      - back

    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always

    ports:
      - 5672:5672 # Port par défaut pour les connexions RabbitMQ
      - 15672:15672 # Port pour le panneau de gestion (UI)

    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/

    networks:
      - back

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c 'npm run start'
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - db
      - rabbitmq
    networks:
      - back

volumes:
  mysql-data:
  rabbitmq-data:
