networks:
  back:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "ng serve --host 0.0.0.0"
    expose:
      - "4200"
    networks:
      - back

  db:
    container_name: database

    image: mariadb:latest
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: administration
      MYSQL_USER: user
      MYSQL_PASSWORD: example

    networks:
      - back

    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql
  
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always

    expose:
      - "5672" # Port par défaut pour les connexions RabbitMQ
    ports:
      - 15672:15672 # Port pour le panneau de gestion (UI)

    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/

    networks:
      - back
  
  producer:
    image: rabbitmq-processor:1.0-${QUARKUS_MODE:-jvm}
    build:
      context: rabbitmq-processor
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

    depends_on:
      - rabbitmq

    networks:
      - back

  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - 1025:1025
    expose:
      - "1080"
      - "1025"
    networks:
      - back

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c 'npm run start'
    expose:
      - "3000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - back

  nginx:
    image: nginx:latest
    depends_on:
      - backend
      - frontend
      - maildev
    ports:
      - "1234:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - back

volumes:
  mysql-data:
  rabbitmq-data:
