services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    ports:
      - 127.0.0.1:3000:3000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "ng serve --host 0.0.0.0"
    ports:
      - 127.0.0.1:4200:4200
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./backend/database.sql:/docker-entrypoint-initdb.d/database.sql

